"""
scrape_catalog.py
=================
Professional full-catalog scraper for texnomart.uz

Architecture:
  CatalogScraper    -- orchestrates categories -> pages -> products
  BatchRepository   -- wraps JsonTemplateProductRepository with slug-cache
                       and handles empty / corrupt JSON files

Features:
  - Paginates every category (MAX_PAGES pages, ~20 products / page)
  - Rich progress bars + live stats table
  - Idempotent: skips slugs already in products.json
  - Batch-saves after every page to survive crashes
  - Configurable polite crawling delay
  - ASCII-safe output (Windows cp1252 compatible)
  - Final summary report

Usage:
  python scrape_catalog.py
  python scrape_catalog.py --max-pages 5 --delay 1.0
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from threading import Lock
from typing import Iterator

# Force UTF-8 stdout so Rich's table borders render correctly on Windows
os.environ.setdefault("PYTHONIOENCODING", "utf-8")

from rich.console import Console
from rich.live import Live
from rich.panel import Panel
from rich.progress import (
    BarColumn,
    MofNCompleteColumn,
    Progress,
    SpinnerColumn,
    TaskID,
    TextColumn,
    TimeElapsedColumn,
)
from rich.table import Table
from rich.text import Text

# ── project imports ───────────────────────────────────────────────────────────
sys.path.insert(0, str(Path(__file__).parent))

from app.domain.entities import ProductInput
from app.infrastructure.http_client import RequestsPageFetcher
from app.infrastructure.json_template_repository import JsonTemplateProductRepository
from app.infrastructure.texnomart_catalog_parser import TexnomartCatalogParser
from app.infrastructure.texnomart_product_parser import TexnomartProductParser

# ── defaults ──────────────────────────────────────────────────────────────────

OUTPUT_PATH = Path("products.json")

CATEGORY_URLS: list[str] = [
    "https://texnomart.uz/katalog/smartfony/",
    "https://texnomart.uz/katalog/knopochnye-telefony/",
    "https://texnomart.uz/katalog/aksessuary-dlya-telefonov/",
    "https://texnomart.uz/katalog/kabeli/",
    "https://texnomart.uz/katalog/zaryadnye-ustroistva/",
    "https://texnomart.uz/katalog/naushniki/",
    "https://texnomart.uz/katalog/gadzhety/",
    "https://texnomart.uz/katalog/noutbuki/",
]

DEFAULT_MAX_PAGES: int = 8
DEFAULT_DELAY: float = 0.6     # seconds between HTTP requests
HTTP_TIMEOUT: int = 25
HTTP_RETRIES: int = 3
BATCH_SIZE: int = 20           # products saved per flush


# ── statistics ────────────────────────────────────────────────────────────────

@dataclass
class CategoryStats:
    slug: str
    pages_visited: int = 0
    urls_found: int = 0
    fetched: int = 0
    saved: int = 0
    skipped: int = 0
    errors: int = 0
    _start: float = field(default_factory=time.monotonic, repr=False)

    @property
    def elapsed(self) -> str:
        secs = int(time.monotonic() - self._start)
        return f"{secs // 60:02d}m{secs % 60:02d}s"


@dataclass
class GlobalStats:
    categories: list[CategoryStats] = field(default_factory=list)
    started_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def total_saved(self) -> int:
        return sum(c.saved for c in self.categories)

    @property
    def total_errors(self) -> int:
        return sum(c.errors for c in self.categories)

    @property
    def total_skipped(self) -> int:
        return sum(c.skipped for c in self.categories)


# ── robust repository wrapper ─────────────────────────────────────────────────

_EMPTY_PAYLOAD: dict = {
    "meta": {
        "source": "texnomart.uz",
        "currency": "UZS",
        "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "created_by_id": 1,
        "notes": "Generated by scrape_catalog.py",
    },
    "reference_data": {"categories": [], "brands": [], "attributes": []},
    "products": [],
}


def _ensure_valid_json(path: Path) -> None:
    """Create or fix an empty / corrupt products.json."""
    if not path.exists() or path.stat().st_size == 0:
        path.write_text(json.dumps(_EMPTY_PAYLOAD, ensure_ascii=False, indent=2), encoding="utf-8")
        return
    try:
        json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        path.write_text(json.dumps(_EMPTY_PAYLOAD, ensure_ascii=False, indent=2), encoding="utf-8")


class BatchRepository:
    """
    Thread-safe product repository with:
    - slug cache (avoids duplicate saves)
    - JSON corruption guard (re-initialises if file is empty/broken)
    """

    def __init__(self, path: Path) -> None:
        _ensure_valid_json(path)
        self._repo = JsonTemplateProductRepository(path)
        self._lock = Lock()
        self._known: set[str] = self._load_slugs(path)

    @staticmethod
    def _load_slugs(path: Path) -> set[str]:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            return {p["slug"] for p in data.get("products", []) if p.get("slug")}
        except Exception:
            return set()

    def is_known(self, slug: str) -> bool:
        return slug in self._known

    def save(self, products: list[ProductInput]) -> int:
        """Persist unseen products. Returns count actually written."""
        novel = [p for p in products if p.slug not in self._known]
        if not novel:
            return 0
        with self._lock:
            # Re-check inside lock to handle concurrent batches
            novel = [p for p in novel if p.slug not in self._known]
            if not novel:
                return 0
            # Guard against corrupt file before write
            _ensure_valid_json(OUTPUT_PATH)
            self._repo.add_or_update_products(novel)
            for p in novel:
                self._known.add(p.slug)
        return len(novel)


# ── URL helpers ───────────────────────────────────────────────────────────────

def page_url(category_url: str, page: int) -> str:
    base = category_url.rstrip("/") + "/"
    return base if page <= 1 else f"{base}?page={page}"


def slug_from_url(url: str) -> str:
    return url.rstrip("/").split("/")[-1] or "unknown"


def batches(lst: list, size: int) -> Iterator[list]:
    for i in range(0, len(lst), size):
        yield lst[i : i + size]


# ── HTTP helpers ──────────────────────────────────────────────────────────────

def fetch_page_urls(
    fetcher: RequestsPageFetcher,
    parser: TexnomartCatalogParser,
    cat_url: str,
    page: int,
    delay: float,
    logger: logging.Logger,
) -> list[str]:
    url = page_url(cat_url, page)
    try:
        html = fetcher.fetch(url)
        time.sleep(delay)
        return parser.parse_product_urls(url, html)
    except Exception as exc:
        logger.warning("[page %d] %s -- %s", page, url, exc)
        return []


def fetch_product(
    fetcher: RequestsPageFetcher,
    parser: TexnomartProductParser,
    product_url: str,
    delay: float,
    logger: logging.Logger,
) -> ProductInput | None:
    try:
        html = fetcher.fetch(product_url)
        time.sleep(delay)
        return parser.parse_product(product_url, html)
    except Exception as exc:
        logger.warning("product error: %s -- %s", product_url, exc)
        return None


# ── Rich UI ───────────────────────────────────────────────────────────────────

def _make_progress() -> Progress:
    return Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(bar_width=28),
        MofNCompleteColumn(),
        TimeElapsedColumn(),
        expand=False,
    )


def _stats_table(stats: GlobalStats, active: str) -> Table:
    tbl = Table(
        title="[bold cyan]Texnomart Catalog Scraper[/]",
        show_lines=True,
        header_style="bold magenta",
        min_width=72,
    )
    tbl.add_column("Category", style="cyan", no_wrap=True, min_width=28)
    tbl.add_column("Pages", justify="right", min_width=5)
    tbl.add_column("URLs",  justify="right", min_width=5)
    tbl.add_column("Saved", justify="right", style="green", min_width=5)
    tbl.add_column("Skip",  justify="right", style="yellow", min_width=5)
    tbl.add_column("Err",   justify="right", style="red", min_width=4)
    tbl.add_column("Time",  justify="right", min_width=7)

    for cs in stats.categories:
        label = Text(cs.slug)
        if cs.slug == active:
            label.stylize("bold")
            label.append(" >>", style="green")
        tbl.add_row(label, str(cs.pages_visited), str(cs.urls_found),
                    str(cs.saved), str(cs.skipped), str(cs.errors), cs.elapsed)

    tbl.add_section()
    tbl.add_row(
        Text("TOTAL", style="bold white"),
        str(sum(c.pages_visited for c in stats.categories)),
        str(sum(c.urls_found   for c in stats.categories)),
        Text(str(stats.total_saved),   style="bold green"),
        Text(str(stats.total_skipped), style="bold yellow"),
        Text(str(stats.total_errors),  style="bold red"),
        "",
    )
    return tbl


def _final_report(stats: GlobalStats, console: Console) -> None:
    dur = datetime.now(timezone.utc) - stats.started_at
    m, s = divmod(int(dur.total_seconds()), 60)

    tbl = Table(show_header=False, box=None, padding=(0, 2))
    tbl.add_column(style="bold white")
    tbl.add_column(style="cyan")
    tbl.add_row("Categories scraped:", str(len(stats.categories)))
    tbl.add_row("Products saved:    ", f"[green]{stats.total_saved}[/]")
    tbl.add_row("Products skipped:  ", f"[yellow]{stats.total_skipped}[/]")
    tbl.add_row("Errors:            ", f"[red]{stats.total_errors}[/]")
    tbl.add_row("Total time:        ", f"{m}m {s}s")
    tbl.add_row("Output:            ", str(OUTPUT_PATH.resolve()))

    console.print(Panel(tbl, title="[bold green]Scraping Complete[/]", border_style="green"))


# ── orchestrator ──────────────────────────────────────────────────────────────

def run(max_pages: int, delay: float) -> None:
    logging.basicConfig(
        level=logging.WARNING,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%H:%M:%S",
        stream=sys.stderr,
    )
    logger = logging.getLogger("scrape_catalog")

    # Force UTF-8 on Windows legacy consoles
    console = Console(highlight=False, emoji=False, markup=True)

    console.print(Panel(
        f"[bold cyan]Texnomart Full-Catalog Scraper[/]\n"
        f"Categories: {len(CATEGORY_URLS)} | "
        f"Max pages/category: {max_pages} | "
        f"Delay: {delay}s | "
        f"Output: {OUTPUT_PATH}",
        border_style="cyan",
    ))

    # ── init ─────────────────────────────────────────────────────────────────
    _ensure_valid_json(OUTPUT_PATH)

    fetcher        = RequestsPageFetcher(timeout=HTTP_TIMEOUT, retries=HTTP_RETRIES)
    catalog_parser = TexnomartCatalogParser()
    repo           = BatchRepository(OUTPUT_PATH)

    console.print(
        f"[yellow]Already saved:[/] [bold]{len(repo._known)}[/] products "
        f"(will be skipped)\n"
    )

    g_stats       = GlobalStats()
    active_cat    = ""
    cat_progress  = _make_progress()
    prod_progress = _make_progress()

    def render() -> Table:
        grid = Table.grid(padding=(0, 0, 1, 0))
        grid.add_row(_stats_table(g_stats, active_cat))
        grid.add_row(cat_progress)
        grid.add_row(prod_progress)
        return grid

    prod_task: TaskID | None = None

    with Live(render(), console=console, refresh_per_second=3) as live:

        cat_task = cat_progress.add_task("[cyan]Categories", total=len(CATEGORY_URLS))

        for cat_url in CATEGORY_URLS:
            cat_slug   = slug_from_url(cat_url)
            active_cat = cat_slug
            cs         = CategoryStats(slug=cat_slug)
            g_stats.categories.append(cs)

            cat_progress.update(cat_task, description=f"[cyan]Category: {cat_slug}")

            # ── 1) collect product URLs across pages ──────────────────────────
            all_urls:   list[str] = []
            seen_urls:  set[str]  = set()
            empty_runs: int       = 0

            for page in range(1, max_pages + 1):
                page_urls = fetch_page_urls(
                    fetcher, catalog_parser, cat_url, page, delay, logger
                )
                cs.pages_visited += 1
                new_urls = [u for u in page_urls if u not in seen_urls]
                seen_urls.update(new_urls)
                all_urls.extend(new_urls)
                cs.urls_found = len(all_urls)

                if new_urls:
                    empty_runs = 0
                else:
                    empty_runs += 1
                    if empty_runs >= 2:
                        break       # no more pages for this category

                live.update(render())

            # ── 2) fetch & parse products, batch-save every BATCH_SIZE ────────
            product_parser = TexnomartProductParser(default_category_slug=cat_slug)

            if prod_task is not None:
                prod_progress.remove_task(prod_task)
            prod_task = prod_progress.add_task(
                f"[green]  {cat_slug}", total=len(all_urls)
            )

            for batch in batches(all_urls, BATCH_SIZE):
                parsed: list[ProductInput] = []

                for product_url in batch:
                    product = fetch_product(
                        fetcher, product_parser, product_url, delay, logger
                    )
                    cs.fetched += 1

                    if product is None:
                        cs.errors += 1
                    elif repo.is_known(product.slug):
                        cs.skipped += 1
                    else:
                        parsed.append(product)

                    prod_progress.update(prod_task, advance=1)
                    live.update(render())

                # Flush batch to disk
                if parsed:
                    saved = repo.save(parsed)
                    cs.saved   += saved
                    cs.skipped += len(parsed) - saved   # within-batch duplicates

                live.update(render())

            cat_progress.update(cat_task, advance=1)
            live.update(render())

        cat_progress.update(cat_task, description="[green]All categories done")

    _final_report(g_stats, console)


# ── CLI entry point ───────────────────────────────────────────────────────────

def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Texnomart full-catalog scraper",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--max-pages", type=int, default=DEFAULT_MAX_PAGES,
        help="Max catalog pages to traverse per category",
    )
    parser.add_argument(
        "--delay", type=float, default=DEFAULT_DELAY,
        help="Seconds to wait between HTTP requests",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    run(max_pages=args.max_pages, delay=args.delay)
